// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reaction-home/Current.tsx": () => import("../components/mockups/reaction-home/Current.tsx"),
  "./components/mockups/reaction-home/HighTech.tsx": () => import("../components/mockups/reaction-home/HighTech.tsx")
};
