import './_group.css';
import { useState } from 'react';
import {
  ArrowUpRight, Brain, Calculator, Check, CircleHelp, Eye, Flame, Gamepad2,
  Hash, LayoutDashboard, Link2, LogIn, Medal, Moon, Palette, Pencil, Puzzle, Search,
  Shuffle, Sparkles, Swords, Sun, Target, Timer, TrendingUp, Trophy, Type, Users,
  Zap,
} from 'lucide-react';

type Icon = typeof Zap;
type Flow = 'arena' | 'single' | 'join' | 'challenge';

const modes: [string, string, Icon, string][] = [
  ['Color', 'Name the color you see', Eye, 'text-chart-4'], ['Memory', 'Remember the sequence', Brain, 'text-primary'],
  ['Math', 'Solve quick arithmetic', Calculator, 'text-chart-3'], ['Reflex', 'Tap when the screen turns green', Zap, 'text-accent'],
  ['Catch It', 'Catch the moving target', Zap, 'text-chart-1'], ['Reverse', 'Type the word backwards', Shuffle, 'text-chart-5'],
  ['Count', 'Count the items quickly', Hash, 'text-chart-1'], ['Sequence', 'Repeat the pattern', Target, 'text-chart-2'],
  ['Stroop', 'Pick the ink color, not the word', Timer, 'text-chart-3'], ['Odd One', 'Spot the odd one out', Users, 'text-accent'],
  ['Scramble', 'Unscramble the word', Type, 'text-chart-1'], ['Impostor', 'Find the different item', Search, 'text-chart-2'],
  ['Chain', 'Continue the number chain', Link2, 'text-primary'], ['Riddles', 'Solve clever riddles', CircleHelp, 'text-chart-5'],
  ['Missing Number', 'Find the missing number', CircleHelp, 'text-chart-4'], ['Color Memory', 'Remember color sequence', Palette, 'text-chart-1'],
  ['Tile Match', 'Match the pairs', Puzzle, 'text-chart-3'], ['Speed Type', 'Type as fast as you can', Type, 'text-chart-2'],
  ['Scribble', 'Draw what you see described', Pencil, 'text-chart-5'], ['Shape Match', 'Find the matching shape', Puzzle, 'text-chart-3'],
  ['Word Hunt', 'Find words in the grid', Search, 'text-chart-1'], ['Whack', 'Test your timing', Zap, 'text-chart-4'],
  ['Treasure', 'Choose the right path', Target, 'text-chart-2'], ['Duel', 'Outscore your rival', Swords, 'text-chart-5'],
  ['Series', 'Complete the number series', TrendingUp, 'text-chart-3'], ['Vowels', 'Spot the missing vowel', Type, 'text-primary'],
  ['Alphabet', 'Race through the alphabet', Type, 'text-chart-4'], ['Color Mix', 'Mix the right colors', Palette, 'text-chart-1'],
  ['Clock', 'Read the clock quickly', Timer, 'text-chart-2'], ['Roman', 'Decode Roman numerals', Hash, 'text-chart-5'],
  ['Palindrome', 'Find the mirrored word', Shuffle, 'text-chart-3'], ['Spelling', 'Spell it correctly', Check, 'text-primary'],
  ['True / False', 'Make the call quickly', Check, 'text-chart-4'], ['Emoji Talk', 'Guess the phrase', Puzzle, 'text-chart-5'],
  ['Number Link', 'Connect the chain', Link2, 'text-chart-2'],
];

const achievements: [string, string, Icon][] = [
  ['First Blood', 'Play your first game', Zap], ['Getting Warm', 'Play 10 games', Gamepad2],
  ['Fifty Strong', 'Play 50 games', Flame], ['Centurion', 'Play 100 games', Trophy],
  ['500 Club', 'Score 500+ in a game', Medal], ['Mode Master', 'Master five modes', Target],
  ['On Fire', 'Build a 10-hit combo', Flame], ['Into the Fray', 'Compete in an arena', Swords],
  ['Arena Victor', 'Win an arena', Trophy], ['Streak Seeker', 'Keep a 3-day streak', Check],
];
const navLinks: [string, Icon][] = [['Dashboard', LayoutDashboard], ['Games', Gamepad2], ['Arena', Swords], ['Leaderboard', Trophy]];

function GameCard({ mode, index }: { mode: typeof modes[number]; index: number }) {
  const [label, description, Icon, color] = mode;
  return <button className="group flex min-h-[145px] flex-col items-start rounded-2xl border border-border/60 bg-card/70 p-4 text-left backdrop-blur-md transition-all hover:-translate-y-1 hover:border-primary/50 hover:bg-card" onClick={() => alert(`${label} selected — ready when you are!`)}>
    <div className="mb-4 flex w-full items-center justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-xl border border-border/60 bg-secondary/60 ${color}`}><Icon className="h-5 w-5" /></div><span className="font-mono text-[10px] text-muted-foreground">0{index + 1}</span></div>
    <span className="font-display text-sm font-bold">{label}</span><span className="mt-1 text-xs leading-snug text-muted-foreground">{description}</span>
  </button>;
}

function Logo() {
  return <div className="flex items-center gap-2.5"><div className="relative flex h-9 w-9 items-center justify-center rounded-xl btn-primary-gradient shadow-lg shadow-[hsl(var(--brand-a)/.35)]"><Zap className="h-5 w-5 text-primary-foreground" fill="currentColor" /></div><div className="leading-none"><p className="font-display text-lg font-bold tracking-tight">Reaction<span className="text-gradient">Arena</span></p><p className="mt-1 text-[9px] font-medium uppercase tracking-[.24em] text-muted-foreground">Fast mind · sharp edge</p></div></div>;
}

export function Current() {
  const [flow, setFlow] = useState<Flow | null>(null);
  const [name, setName] = useState('');
  const [code, setCode] = useState('');
  const [light, setLight] = useState(false);
  const open = (next: Flow) => { setFlow(next); setCode(''); };
  const go = () => { if (name.trim() && (flow === 'single' || code.trim())) setFlow(null); };
  const featured = modes.slice(0, 4);
  return <div className={`reaction-home ${light ? 'light' : ''}`}>
    <div className="pointer-events-none fixed inset-0 z-0 bg-grid opacity-70" />
    <div className="pointer-events-none fixed inset-x-0 top-0 z-0 h-80 bg-gradient-to-b from-brand-a/[.07] to-transparent" />
    <header className="sticky top-0 z-40 border-b border-border/50 bg-background/70 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><Logo /></button><nav className="hidden items-center gap-1 rounded-full border border-border/60 bg-card/50 p-1 md:flex">{navLinks.map(([text, Icon]) => <button key={text} className={`flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${text === 'Dashboard' ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-secondary/70 hover:text-foreground'}`} onClick={() => text === 'Games' ? document.getElementById('library')?.scrollIntoView({ behavior: 'smooth' }) : undefined}><Icon className="h-4 w-4" />{text}</button>)}</nav><div className="flex items-center gap-2"><button aria-label="Toggle theme" onClick={() => setLight(!light)} className="rounded-lg border border-border bg-card p-2 text-muted-foreground hover:text-foreground">{light ? <Moon className="h-4 w-4" /> : <Sun className="h-4 w-4" />}</button></div></div></header>
    <main className="relative z-10 mx-auto w-full max-w-6xl px-4 sm:px-6">
      <section className="relative py-14 sm:py-20"><div className="mx-auto max-w-3xl text-center"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/[.08] px-4 py-1.5 text-xs font-semibold text-primary"><Sparkles className="h-3.5 w-3.5" />Your daily competitive ritual</div><h1 className="text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-7xl">Train fast.<br /><span className="text-gradient">Think sharper.</span></h1><p className="mx-auto mt-6 max-w-xl text-base leading-relaxed text-muted-foreground sm:text-lg">A focused arena for quick minds. Pick a mode, challenge your friends, and make every reaction count.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><button className="btn-primary-gradient inline-flex items-center gap-2 rounded-lg px-8 py-3 text-base font-semibold text-primary-foreground shadow-lg" onClick={() => open('single')}><Gamepad2 className="h-5 w-5" />Start practicing</button><button className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-8 py-3 text-base font-semibold hover:bg-secondary" onClick={() => open('arena')}><Swords className="h-5 w-5" />Host an arena</button></div><button className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground underline-offset-4 hover:text-primary hover:underline" onClick={() => open('challenge')}><Medal className="h-4 w-4" />Have a challenge code? Enter it</button><div className="mt-12 grid grid-cols-3 divide-x divide-border/60 rounded-2xl border border-border/60 bg-card/50 py-5 backdrop-blur-md">{[['35', 'Game modes'], ['8', 'Players / arena'], ['15', 'Sec / round']].map(([v, l]) => <div key={l} className="px-4 text-center"><p className="font-display text-2xl font-bold sm:text-3xl">{v}</p><p className="mt-1 text-[11px] font-medium uppercase tracking-[.16em] text-muted-foreground">{l}</p></div>)}</div></div></section>
      <section className="pb-8"><div className="glass flex flex-col gap-5 rounded-2xl border border-border/60 p-5 sm:flex-row sm:items-center"><div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-primary/25 bg-primary/10 text-primary"><Trophy className="h-7 w-7" /></div><div className="flex-1"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Your profile</p><h2 className="mt-1 font-display text-xl font-bold">Welcome back, Alex</h2><p className="text-sm text-muted-foreground">Level 4 Contender · 680 XP total</p></div><div className="w-full sm:w-48"><div className="mb-2 flex justify-between text-xs text-muted-foreground"><span>Progress to level 5</span><span>40%</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full w-2/5 rounded-full btn-primary-gradient" /></div></div></div></section>
      <section className="pb-10"><div className="mb-4 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-chart-1/30 bg-chart-1/10"><Medal className="h-5 w-5 text-chart-1" /></div><div><h2 className="font-display text-xl font-bold">Achievements</h2><p className="text-xs text-muted-foreground">5/20 collected</p></div></div><div className="rounded-2xl border border-border/60 bg-card/70 p-5"><div className="mb-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full w-1/4 rounded-full btn-primary-gradient" /></div><div className="mt-4 grid grid-cols-5 gap-2 sm:grid-cols-8 md:grid-cols-10">{achievements.map(([title, desc, Icon], i) => <div key={title} title={`${title} — ${desc}`} className={`flex flex-col items-center gap-1 rounded-xl border p-2 text-center ${i < 5 ? 'border-chart-1/30 bg-chart-1/[.08]' : 'border-border/40 opacity-60'}`}><Icon className={`h-5 w-5 ${i < 5 ? 'text-chart-1' : 'text-muted-foreground'}`} /><span className="text-[10px] font-semibold leading-tight text-muted-foreground">{title}</span></div>)}</div></div></section>
      <section className="pb-10"><button onClick={() => alert('Daily challenge opened')} className="relative flex w-full flex-col gap-5 overflow-hidden rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/[.12] via-card to-brand-c/[.12] p-6 text-left transition hover:border-primary/50 sm:flex-row sm:items-center"><div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-primary/25 bg-card/80"><Flame className="h-7 w-7 text-chart-4" /></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Daily Challenge</p><span className="rounded-full border border-chart-4/30 bg-chart-4/10 px-2 py-0.5 text-xs font-bold text-chart-4">4-day streak</span></div><h2 className="mt-1 font-display text-xl font-bold">Today: Reflex</h2><p className="text-sm text-muted-foreground">One game, same for everyone. Keep the streak alive →</p></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="font-display text-2xl font-bold text-primary">842</p><p className="text-[11px] uppercase tracking-widest text-muted-foreground">best score</p></div><span className="btn-primary-gradient rounded-lg px-5 py-3 font-semibold text-primary-foreground">Play now</span></div></button></section>
      <section className="pb-10"><div className="rounded-2xl border border-border/60 bg-card/70 p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Weekly recap</p><h2 className="mt-1 font-display text-xl font-bold">A sharp week so far</h2></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">This week</span></div><div className="grid grid-cols-3 gap-3 sm:grid-cols-6">{[['24', 'Games'], ['4', 'Active days'], ['6,420', 'XP earned'], ['82%', 'Accuracy'], ['12', 'Best combo'], ['#18', 'Rank']].map(([value, label]) => <div key={label} className="rounded-xl bg-secondary/60 p-3"><p className="font-display text-lg font-bold">{value}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p></div>)}</div></div></section>
      <section className="pb-10"><div className="grid gap-4 md:grid-cols-3">{[['Host Arena', 'Create a room & invite friends to compete', Swords, 'Create room', 'arena'], ['Join Arena', 'Enter a room code to battle friends', LogIn, 'Enter code', 'join'], ['Solo Practice', 'Pick a single game mode to play alone', Gamepad2, 'Browse games', 'single']].map(([title, desc, Icon, action, target]) => <button key={String(title)} onClick={() => open(target as Flow)} className="group flex min-h-[190px] flex-col items-start gap-4 rounded-2xl border border-border/60 bg-card/70 p-6 text-left transition hover:-translate-y-1 hover:border-primary/50"><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><Icon className="h-6 w-6" /></div><div className="flex-1"><h3 className="font-display text-lg font-bold">{String(title)}</h3><p className="mt-1 text-sm text-muted-foreground">{String(desc)}</p></div><div className="flex w-full items-center justify-between text-sm font-semibold text-primary">{String(action)}<ArrowUpRight className="h-4 w-4" /></div></button>)}</div></section>
      <section className="pb-10"><div className="mb-5 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-border/60 bg-secondary/60"><TrendingUp className="h-5 w-5 text-primary" /></div><div><h2 className="font-display text-xl font-bold">Your progress</h2><p className="text-xs text-muted-foreground">Activity stored locally on this device</p></div></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Games played', '24', Zap, 'text-primary'], ['Best score', '1,284', Trophy, 'text-chart-2'], ['Arenas played', '8', Swords, 'text-chart-3'], ['Arena wins', '5', Flame, 'text-chart-4']].map(([l, v, Icon, c]) => <div key={String(l)} className="rounded-2xl border border-border/60 bg-card/70 p-5"><Icon className={`mb-6 h-5 w-5 ${c}`} /><p className="font-display text-3xl font-bold">{String(v)}</p><p className="mt-1 text-xs text-muted-foreground">{String(l)}</p></div>)}</div></section>
      <section className="pb-10"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Featured</p><h2 className="mt-1 font-display text-xl font-bold">Trending right now</h2></div><button onClick={() => document.getElementById('library')?.scrollIntoView({ behavior: 'smooth' })} className="flex items-center gap-1 text-sm font-semibold text-primary">View all <ArrowUpRight className="h-4 w-4" /></button></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{featured.map((m, i) => <GameCard key={m[0]} mode={m} index={i} />)}</div></section>
      <section id="library" className="pb-16"><div className="mb-5 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-border/60 bg-secondary/60"><Target className="h-5 w-5 text-primary" /></div><div><h2 className="font-display text-xl font-bold">The full library</h2><p className="text-xs text-muted-foreground">35 modes to sharpen every edge</p></div></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{modes.map((m, i) => <GameCard key={m[0]} mode={m} index={i} />)}</div></section>
      <section className="relative pb-16"><div className="relative overflow-hidden rounded-3xl border border-border/60 bg-gradient-to-br from-brand-a/[.12] via-card to-brand-c/[.12] p-8 sm:p-12"><div className="relative text-center"><div className="btn-primary-gradient mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl shadow-xl"><Users className="h-7 w-7 text-primary-foreground" /></div><h2 className="font-display text-3xl font-bold sm:text-4xl">Ready to raise the <span className="text-gradient">stakes?</span></h2><p className="mx-auto mt-3 max-w-md text-sm text-muted-foreground sm:text-base">Invite up to 8 friends, race across randomly selected games, and crown the fastest mind in the room.</p><button className="btn-primary-gradient mt-7 rounded-lg px-8 py-3 text-base font-semibold text-primary-foreground" onClick={() => open('arena')}><Zap className="mr-2 inline h-5 w-5" />Host your arena</button></div></div></section>
    </main>
    <footer className="relative z-10 border-t border-border/50 py-6"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-3 px-4 text-xs text-muted-foreground sm:flex-row sm:px-6"><p>ReactionArena — train fast, think sharper.</p><p>35 modes · Up to 8 players per arena</p></div></footer>
    {flow && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={() => setFlow(null)}><div className="w-full max-w-md rounded-2xl border border-border bg-popover p-6 shadow-2xl" onClick={e => e.stopPropagation()}><div className="mb-5"><h2 className="font-display text-2xl font-bold">{flow === 'join' ? 'Join an Arena' : flow === 'challenge' ? 'Enter a Challenge Code' : flow === 'arena' ? 'Host an Arena' : 'Solo Practice'}</h2><p className="mt-1 text-sm text-muted-foreground">{flow === 'join' ? 'Enter your name and the room code' : flow === 'challenge' ? "Enter your name and a friend's challenge code" : 'Enter your player name to get started'}</p></div><input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Your name" className="mb-3 w-full rounded-lg border border-input bg-background px-3 py-3 text-sm outline-none focus:border-primary" />{(flow === 'join' || flow === 'challenge') && <input value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder={flow === 'join' ? 'Room code (e.g. AB3XY)' : 'Challenge code (e.g. 5K3PQ)'} maxLength={5} className="mb-3 w-full rounded-lg border border-input bg-background px-3 py-3 text-center font-mono text-xl tracking-[.3em] outline-none focus:border-primary" />}<button disabled={!name.trim() || ((flow === 'join' || flow === 'challenge') && !code.trim())} onClick={go} className="w-full rounded-lg btn-primary-gradient py-3 font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">{flow === 'join' ? 'Join Room' : flow === 'challenge' ? 'Accept Challenge' : flow === 'arena' ? "Let's Go!" : 'Start Playing'}</button></div></div>}
  </div>;
}